# Generated by Django 5.0.1 on 2024-01-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_touristreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/review_images/'),
        ),
    ]
